nu=int(input("Introdu primul numar:"))
nd=int(input("Introdu al doilea numar:"))
nt=int(input("Introdu al treilea numar:"))
print(nu,nd,nt,sep="")
print(nu,nt,nd,sep="")
print(nt,nu,nd,sep="")
print(nd,nu,nt,sep="")
print(nt,nd,nu,sep="")