nu=int(input("Introdu primul numar:"))
nd=int(input("Introdu al doilea numar:"))
nt=int(input("Introdu al treilea numar:"))
print(nu,"+",nd,"=",nu+nd,sep="")
print(nd,"+",nt,"=",nd+nt,sep="")
print(nu,"+",nt,"=",nu+nt,sep="")